/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as StopStopIdRouteImport } from './routes/stop.$stopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const StopStopIdRoute = StopStopIdRouteImport.update({
  id: '/stop/$stopId',
  path: '/stop/$stopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nearby': typeof NearbyRoute
  '/stop/$stopId': typeof StopStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nearby': typeof NearbyRoute
  '/stop/$stopId': typeof StopStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nearby': typeof NearbyRoute
  '/stop/$stopId': typeof StopStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nearby' | '/stop/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nearby' | '/stop/$stopId'
  id: '__root__' | '/' | '/nearby' | '/stop/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NearbyRoute: typeof NearbyRoute
  StopStopIdRoute: typeof StopStopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop/$stopId': {
      id: '/stop/$stopId'
      path: '/stop/$stopId'
      fullPath: '/stop/$stopId'
      preLoaderRoute: typeof StopStopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NearbyRoute: NearbyRoute,
  StopStopIdRoute: StopStopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
